USE [master]
GO
/****** Object:  Database [CAMPO]    Script Date: 18/4/2026 20:51:37 ******/
CREATE DATABASE [CAMPO]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CAMPO', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\CAMPO.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CAMPO_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\CAMPO_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [CAMPO] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CAMPO].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [CAMPO] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [CAMPO] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [CAMPO] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [CAMPO] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [CAMPO] SET ARITHABORT OFF 
GO
ALTER DATABASE [CAMPO] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [CAMPO] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [CAMPO] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [CAMPO] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [CAMPO] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [CAMPO] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [CAMPO] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [CAMPO] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [CAMPO] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [CAMPO] SET  DISABLE_BROKER 
GO
ALTER DATABASE [CAMPO] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [CAMPO] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [CAMPO] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [CAMPO] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [CAMPO] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [CAMPO] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [CAMPO] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [CAMPO] SET RECOVERY FULL 
GO
ALTER DATABASE [CAMPO] SET  MULTI_USER 
GO
ALTER DATABASE [CAMPO] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [CAMPO] SET DB_CHAINING OFF 
GO
ALTER DATABASE [CAMPO] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [CAMPO] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [CAMPO] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [CAMPO] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'CAMPO', N'ON'
GO
ALTER DATABASE [CAMPO] SET QUERY_STORE = ON
GO
ALTER DATABASE [CAMPO] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [CAMPO]
GO
/****** Object:  Table [dbo].[AUDITORIA]    Script Date: 18/4/2026 20:51:37 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AUDITORIA](
	[AUDITORIA_ID] [int] NOT NULL,
	[TABLA] [varchar](50) NULL,
	[REGISTRO_ID] [int] NULL,
	[CAMPO] [varchar](50) NULL,
	[VALOR_ANTERIOR] [varchar](50) NULL,
	[VALOR_NUEVO] [varchar](50) NULL,
	[USUARIO_ID] [int] NULL,
	[FECHA] [datetime] NULL,
 CONSTRAINT [PK_AUDITORIA] PRIMARY KEY CLUSTERED 
(
	[AUDITORIA_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BITACORA]    Script Date: 18/4/2026 20:51:37 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BITACORA](
	[BITACORA_ID] [int] NOT NULL,
	[USUARIO_ID] [int] NOT NULL,
	[FECHA] [datetime] NOT NULL,
	[ACTIVIDAD] [varchar](50) NOT NULL,
	[CRITICIDAD_ID] [int] NOT NULL,
 CONSTRAINT [PK_BITACORA] PRIMARY KEY CLUSTERED 
(
	[BITACORA_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CRITICIDAD]    Script Date: 18/4/2026 20:51:37 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CRITICIDAD](
	[CRITICIDAD_ID] [int] NOT NULL,
	[CRITICIDAD] [varchar](50) NOT NULL,
 CONSTRAINT [PK_CRITICIDAD] PRIMARY KEY CLUSTERED 
(
	[CRITICIDAD_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[IDIOMA]    Script Date: 18/4/2026 20:51:37 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[IDIOMA](
	[IDIOMA_ID] [int] NOT NULL,
	[NOMBRE] [varchar](50) NULL,
 CONSTRAINT [PK_IDIOMA] PRIMARY KEY CLUSTERED 
(
	[IDIOMA_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PERFIL]    Script Date: 18/4/2026 20:51:37 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PERFIL](
	[PERFIL_ID] [int] NOT NULL,
	[NOMBRE] [varchar](50) NOT NULL,
 CONSTRAINT [PK_PERFIL] PRIMARY KEY CLUSTERED 
(
	[PERFIL_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PERFIL_PERMISO]    Script Date: 18/4/2026 20:51:37 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PERFIL_PERMISO](
	[PERFIL_ID] [int] NOT NULL,
	[PERMISO_ID] [int] NOT NULL,
 CONSTRAINT [PK_PERFIL_PERMISO] PRIMARY KEY CLUSTERED 
(
	[PERFIL_ID] ASC,
	[PERMISO_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PERMISO]    Script Date: 18/4/2026 20:51:37 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PERMISO](
	[PERMISO_ID] [int] NOT NULL,
	[NOMBRE] [varchar](50) NULL,
	[TIPO] [varchar](50) NULL,
 CONSTRAINT [PK_PERMISO] PRIMARY KEY CLUSTERED 
(
	[PERMISO_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PERMISO_RELACION]    Script Date: 18/4/2026 20:51:37 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PERMISO_RELACION](
	[PERMISO_PADRE_ID] [int] NOT NULL,
	[PERMISO_HIJO_ID] [int] NOT NULL,
 CONSTRAINT [PK_PERMISO_RELACION] PRIMARY KEY CLUSTERED 
(
	[PERMISO_PADRE_ID] ASC,
	[PERMISO_HIJO_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SESION]    Script Date: 18/4/2026 20:51:37 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SESION](
	[SESION_ID] [int] NULL,
	[USUARIO_ID] [int] NULL,
	[FECHA_LOGIN] [datetime] NULL,
	[FECHA_LOGOUT] [datetime] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TRADUCCION]    Script Date: 18/4/2026 20:51:37 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TRADUCCION](
	[TRADUCCION_ID] [int] NOT NULL,
	[CLAVE] [varchar](50) NULL,
	[IDIOMA_ID] [int] NULL,
	[TEXTO] [varchar](50) NULL,
 CONSTRAINT [PK_TRADUCCION] PRIMARY KEY CLUSTERED 
(
	[TRADUCCION_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USUARIO]    Script Date: 18/4/2026 20:51:37 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USUARIO](
	[USUARIO_ID] [int] NOT NULL,
	[NOMBRE] [varchar](50) NULL,
	[APELLIDO] [varchar](50) NULL,
	[USUARIO] [varchar](50) NOT NULL,
	[PASS_HASH] [varchar](max) NOT NULL,
	[BORRADO] [int] NOT NULL,
	[SALT] [varchar](50) NULL,
	[IDIOMA_ID] [int] NULL,
	[INTENTOS] [int] NULL,
 CONSTRAINT [PK_USUARIO] PRIMARY KEY CLUSTERED 
(
	[USUARIO_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USUARIO_PERFIL]    Script Date: 18/4/2026 20:51:37 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USUARIO_PERFIL](
	[USUARIO_ID] [int] NOT NULL,
	[PERFIL_ID] [int] NOT NULL,
 CONSTRAINT [PK_USUARIO_PERFIL] PRIMARY KEY CLUSTERED 
(
	[USUARIO_ID] ASC,
	[PERFIL_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AUDITORIA]  WITH CHECK ADD  CONSTRAINT [FK_AUDITORIA_USUARIO] FOREIGN KEY([USUARIO_ID])
REFERENCES [dbo].[USUARIO] ([USUARIO_ID])
GO
ALTER TABLE [dbo].[AUDITORIA] CHECK CONSTRAINT [FK_AUDITORIA_USUARIO]
GO
ALTER TABLE [dbo].[BITACORA]  WITH CHECK ADD  CONSTRAINT [FK_BITACORA_CRITICIDAD] FOREIGN KEY([CRITICIDAD_ID])
REFERENCES [dbo].[CRITICIDAD] ([CRITICIDAD_ID])
GO
ALTER TABLE [dbo].[BITACORA] CHECK CONSTRAINT [FK_BITACORA_CRITICIDAD]
GO
ALTER TABLE [dbo].[BITACORA]  WITH CHECK ADD  CONSTRAINT [FK_BITACORA_USUARIO] FOREIGN KEY([USUARIO_ID])
REFERENCES [dbo].[USUARIO] ([USUARIO_ID])
GO
ALTER TABLE [dbo].[BITACORA] CHECK CONSTRAINT [FK_BITACORA_USUARIO]
GO
ALTER TABLE [dbo].[PERFIL_PERMISO]  WITH CHECK ADD  CONSTRAINT [FK_PERFIL_PERMISO_PERFIL] FOREIGN KEY([PERMISO_ID])
REFERENCES [dbo].[PERFIL] ([PERFIL_ID])
GO
ALTER TABLE [dbo].[PERFIL_PERMISO] CHECK CONSTRAINT [FK_PERFIL_PERMISO_PERFIL]
GO
ALTER TABLE [dbo].[PERFIL_PERMISO]  WITH CHECK ADD  CONSTRAINT [FK_PERFIL_PERMISO_PERMISO] FOREIGN KEY([PERMISO_ID])
REFERENCES [dbo].[PERMISO] ([PERMISO_ID])
GO
ALTER TABLE [dbo].[PERFIL_PERMISO] CHECK CONSTRAINT [FK_PERFIL_PERMISO_PERMISO]
GO
ALTER TABLE [dbo].[SESION]  WITH CHECK ADD  CONSTRAINT [FK_SESION_USUARIO] FOREIGN KEY([USUARIO_ID])
REFERENCES [dbo].[USUARIO] ([USUARIO_ID])
GO
ALTER TABLE [dbo].[SESION] CHECK CONSTRAINT [FK_SESION_USUARIO]
GO
ALTER TABLE [dbo].[TRADUCCION]  WITH CHECK ADD  CONSTRAINT [FK_TRADUCCION_IDIOMA] FOREIGN KEY([IDIOMA_ID])
REFERENCES [dbo].[IDIOMA] ([IDIOMA_ID])
GO
ALTER TABLE [dbo].[TRADUCCION] CHECK CONSTRAINT [FK_TRADUCCION_IDIOMA]
GO
ALTER TABLE [dbo].[USUARIO]  WITH CHECK ADD  CONSTRAINT [FK_USUARIO_IDIOMA] FOREIGN KEY([IDIOMA_ID])
REFERENCES [dbo].[IDIOMA] ([IDIOMA_ID])
GO
ALTER TABLE [dbo].[USUARIO] CHECK CONSTRAINT [FK_USUARIO_IDIOMA]
GO
ALTER TABLE [dbo].[USUARIO_PERFIL]  WITH CHECK ADD  CONSTRAINT [FK_USUARIO_PERFIL_USUARIO] FOREIGN KEY([USUARIO_ID])
REFERENCES [dbo].[USUARIO] ([USUARIO_ID])
GO
ALTER TABLE [dbo].[USUARIO_PERFIL] CHECK CONSTRAINT [FK_USUARIO_PERFIL_USUARIO]
GO
/****** Object:  StoredProcedure [dbo].[AgregarIntento]    Script Date: 18/4/2026 20:51:37 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[AgregarIntento]
    @id int
AS
BEGIN
    UPDATE USUARIO
    SET INTENTOS = (SELECT ISNULL(INTENTOS, 0) FROM USUARIO WHERE USUARIO_ID = @id) + 1
    WHERE USUARIO_ID = @id
END
GO
/****** Object:  StoredProcedure [dbo].[InsertarBitacora]    Script Date: 18/4/2026 20:51:37 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[InsertarBitacora]
    @usuario INT,
    @fecha DATETIME,
    @actividad VARCHAR(50),
    @criticidad INT
AS
BEGIN
    DECLARE @id int
    SET @id = (SELECT ISNULL(MAX(BITACORA_ID), 0) + 1 FROM BITACORA)

    INSERT INTO Bitacora (BITACORA_ID, USUARIO_ID, Fecha, Actividad, CRITICIDAD_ID)
    VALUES (@id, @usuario, @fecha, @actividad, @criticidad)
END
GO
/****** Object:  StoredProcedure [dbo].[ListarBitacoraFiltrado]    Script Date: 18/4/2026 20:51:37 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[ListarBitacoraFiltrado]
    @usuarioId INT = NULL,
    @fechaInicio DATETIME = NULL,
    @fechaFin DATETIME = NULL,
    @criticidad INT = NULL,
    @actividad NVARCHAR(255) = NULL
AS
BEGIN
    SELECT BITACORA_ID, USUARIO_ID, FECHA, ACTIVIDAD, CRITICIDAD_ID
    FROM Bitacora
    WHERE 
        (@usuarioId IS NULL OR USUARIO_ID = @usuarioId)
        AND (@fechaInicio IS NULL OR Fecha >= @fechaInicio)
        AND (@fechaFin IS NULL OR Fecha <= @fechaFin)
        AND (@criticidad IS NULL OR CRITICIDAD_ID = @criticidad)
        AND (@actividad IS NULL OR Actividad LIKE '%' + @actividad + '%')
    ORDER BY Fecha DESC
END
GO
/****** Object:  StoredProcedure [dbo].[ListarUsuario]    Script Date: 18/4/2026 20:51:37 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[ListarUsuario]
AS
BEGIN
SELECT * FROM USUARIO
END
GO
/****** Object:  StoredProcedure [dbo].[ReestablecerIntentos]    Script Date: 18/4/2026 20:51:37 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[ReestablecerIntentos]
    @id int
AS
BEGIN
    UPDATE USUARIO
    SET INTENTOS = 0
    WHERE USUARIO_ID = @id
END
GO
/****** Object:  StoredProcedure [dbo].[TraerPass]    Script Date: 18/4/2026 20:51:37 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[TraerPass]
    @user varchar(50)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT PASS_HASH, SALT
    FROM USUARIO
    WHERE USUARIO = @user
      AND BORRADO = 0;
END
GO
USE [master]
GO
ALTER DATABASE [CAMPO] SET  READ_WRITE 
GO
